server.port=8082
spring.application.name=backend
spring.datasource.url=jdbc:mysql://116.62.82.244:3306/wealthadvisor?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
spring.datasource.username=remote_admin
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# MyBatis??
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.example.backend.entity

# Spring Session JDBC ?????????????
spring.session.store-type=jdbc
# ????????????30??
spring.session.timeout=1800
# ??????????????always=?????never=??????????SQL?
spring.session.jdbc.initialize-schema=always

pagehelper.helperDialect=mysql
pagehelper.reasonable=true
pagehelper.supportMethodsArguments=true
pagehelper.params=count=countSql

# DeepSeek LLM
deepseek.api.base-url=https://api.deepseek.com
deepseek.api.model=deepseek-chat
deepseek.api.key=sk-b5c1ecac44404c76820808e7d38adc59

# Python配置
# 如果Python不在系统PATH中，可以指定完整路径，例如: python.executable=C:/Python39/python.exe
# 如果留空，将自动检测系统PATH中的python/python3/py命令
python.executable=D:/anaconda/python.exe
